apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-helm
  namespace: pipeline-helm
spec:
  params: []
  resources: []
  workspaces:
    - name: compartido
      optional: false
  tasks:
    - name: task-install-chart
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: task-install-chart
      params:
        - name: charts_dir
          value: bitnami/wordpress
        - name: release_version
          value: v1.0.0
        - name: release_name
          value: helm-release
        - name: values_file
          value: values.yaml
        - name: helm_image
          value: >-
            docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae
      workspaces:
        - name: source
          workspace: compartido
    - name: git-clone
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: 'https://github.com/Evanticks/charts-bitnami.git'
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: compartido
  finally: []